package mx.consultoria.juridica.especializada.config;

public class Prueba_Git {
// Esta clase no se ocupa solo se crea para hacer la prueba de git
/*
 * -----------------------------------------------------------------------------
 
CREATE TABLE HISTORICO_CASOS (
	ID_HISTORICO_CASOS NUMBER (11),
	USUARIO_ALTA VARCHAR2(50 BYTE), 
	FECHA_REGISTRO TIMESTAMP (6),
	NOMBRE_ARCHIVO VARCHAR2(100 BYTE), 
	DOCUMENTO BLOB
);
COMMIT;


ALTER TABLE CONSULTORIAJURIDICA.HISTORICO_CASOS 
ADD CONSTRAINT PK_HISTORICO_CASOS PRIMARY KEY (ID_HISTORICO_CASOS);  
COMMIT;



--SECUENCIA TABLA HISTORICO_CASOS
CREATE SEQUENCE SEQ_HISTORICO_CASOS START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 MINVALUE 1;
COMMIT;


--TRIGGER TABLA CLIENTE
  CREATE OR REPLACE TRIGGER TRG_HISTORICO_CASOS
	BEFORE INSERT ON HISTORICO_CASOS
	FOR EACH ROW  
	  WHEN (new.ID_HISTORICO_CASOS IS NULL)  
	 BEGIN 
	 :new.ID_HISTORICO_CASOS := SEQ_HISTORICO_CASOS.NEXTVAL;
	END;
	COMMIT;

 * 
 */

	
}
