package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Abogado generated by hbm2java
 */
@Entity
@Table(name = "ABOGADO", schema = "CONSULTORIAJURIDICA")
public class Abogado implements java.io.Serializable {

	private long idAbogado;
	private String nombre;
	private String cedulaProfesional;
	private Long numeroCelular;
	private String ciudad;
	private String estadoRadicacion;
	private Set<AsunAbogClien> asunAbogCliens = new HashSet<AsunAbogClien>(0);

	public Abogado() {
	}

	public Abogado(long idAbogado) {
		this.idAbogado = idAbogado;
	}

	public Abogado(long idAbogado, String nombre, String cedulaProfesional, Long numeroCelular, String ciudad,
			String estadoRadicacion, Set<AsunAbogClien> asunAbogCliens) {
		this.idAbogado = idAbogado;
		this.nombre = nombre;
		this.cedulaProfesional = cedulaProfesional;
		this.numeroCelular = numeroCelular;
		this.ciudad = ciudad;
		this.estadoRadicacion = estadoRadicacion;
		this.asunAbogCliens = asunAbogCliens;
	}

	@Id

	@Column(name = "ID_ABOGADO", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdAbogado() {
		return this.idAbogado;
	}

	public void setIdAbogado(long idAbogado) {
		this.idAbogado = idAbogado;
	}

	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CEDULA_PROFESIONAL", length = 13)
	public String getCedulaProfesional() {
		return this.cedulaProfesional;
	}

	public void setCedulaProfesional(String cedulaProfesional) {
		this.cedulaProfesional = cedulaProfesional;
	}

	@Column(name = "NUMERO_CELULAR", precision = 15, scale = 0)
	public Long getNumeroCelular() {
		return this.numeroCelular;
	}

	public void setNumeroCelular(Long numeroCelular) {
		this.numeroCelular = numeroCelular;
	}

	@Column(name = "CIUDAD", length = 50)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "ESTADO_RADICACION", length = 50)
	public String getEstadoRadicacion() {
		return this.estadoRadicacion;
	}

	public void setEstadoRadicacion(String estadoRadicacion) {
		this.estadoRadicacion = estadoRadicacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "abogado")
	public Set<AsunAbogClien> getAsunAbogCliens() {
		return this.asunAbogCliens;
	}

	public void setAsunAbogCliens(Set<AsunAbogClien> asunAbogCliens) {
		this.asunAbogCliens = asunAbogCliens;
	}

}
