package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccesoUsuariosId generated by hbm2java
 */
@Embeddable
public class AccesoUsuariosId implements java.io.Serializable {

	private long idUser;
	private String username;
	private String password;
	private Boolean roleUser;
	private String habilitado;

	public AccesoUsuariosId() {
	}

	public AccesoUsuariosId(long idUser) {
		this.idUser = idUser;
	}

	public AccesoUsuariosId(long idUser, String username, String password, Boolean roleUser, String habilitado) {
		this.idUser = idUser;
		this.username = username;
		this.password = password;
		this.roleUser = roleUser;
		this.habilitado = habilitado;
	}

	@Column(name = "ID_USER", nullable = false, precision = 11, scale = 0)
	public long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(long idUser) {
		this.idUser = idUser;
	}

	@Column(name = "USERNAME", length = 200)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "PASSWORD", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ROLE_USER", precision = 1, scale = 0)
	public Boolean getRoleUser() {
		return this.roleUser;
	}

	public void setRoleUser(Boolean roleUser) {
		this.roleUser = roleUser;
	}

	@Column(name = "HABILITADO", length = 1)
	public String getHabilitado() {
		return this.habilitado;
	}

	public void setHabilitado(String habilitado) {
		this.habilitado = habilitado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccesoUsuariosId))
			return false;
		AccesoUsuariosId castOther = (AccesoUsuariosId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getPassword() == castOther.getPassword()) || (this.getPassword() != null
						&& castOther.getPassword() != null && this.getPassword().equals(castOther.getPassword())))
				&& ((this.getRoleUser() == castOther.getRoleUser()) || (this.getRoleUser() != null
						&& castOther.getRoleUser() != null && this.getRoleUser().equals(castOther.getRoleUser())))
				&& ((this.getHabilitado() == castOther.getHabilitado())
						|| (this.getHabilitado() != null && castOther.getHabilitado() != null
								&& this.getHabilitado().equals(castOther.getHabilitado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdUser();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37 * result + (getRoleUser() == null ? 0 : this.getRoleUser().hashCode());
		result = 37 * result + (getHabilitado() == null ? 0 : this.getHabilitado().hashCode());
		return result;
	}

}
