package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AccesoUsuarios generated by hbm2java
 */
@Entity
@Table(name = "ACCESO_USUARIOS", schema = "CONSULTORIAJURIDICA")
public class AccesoUsuarios implements java.io.Serializable {

	private AccesoUsuariosId id;

	public AccesoUsuarios() {
	}

	public AccesoUsuarios(AccesoUsuariosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "ID_USER", nullable = false, precision = 11, scale = 0)),
			@AttributeOverride(name = "username", column = @Column(name = "USERNAME", length = 200)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)),
			@AttributeOverride(name = "roleUser", column = @Column(name = "ROLE_USER", precision = 1, scale = 0)),
			@AttributeOverride(name = "habilitado", column = @Column(name = "HABILITADO", length = 1)) })
	public AccesoUsuariosId getId() {
		return this.id;
	}

	public void setId(AccesoUsuariosId id) {
		this.id = id;
	}

}
