package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asunto generated by hbm2java
 */
@Entity
@Table(name = "ASUNTO", schema = "CONSULTORIAJURIDICA")
public class Asunto implements java.io.Serializable {

	private long idAsunto;
	private Secretaria secretaria;
	private CatalogoJuzgado catalogoJuzgado;
	private String tipoAsunto;
	private String ciudad;
	private String numeroExpediente;
	private Set<AsunAbogClien> asunAbogCliens = new HashSet<AsunAbogClien>(0);

	public Asunto() {
	}

	public Asunto(long idAsunto, Secretaria secretaria, CatalogoJuzgado catalogoJuzgado) {
		this.idAsunto = idAsunto;
		this.secretaria = secretaria;
		this.catalogoJuzgado = catalogoJuzgado;
	}

	public Asunto(long idAsunto, Secretaria secretaria, CatalogoJuzgado catalogoJuzgado, String tipoAsunto,
			String ciudad, String numeroExpediente, Set<AsunAbogClien> asunAbogCliens) {
		this.idAsunto = idAsunto;
		this.secretaria = secretaria;
		this.catalogoJuzgado = catalogoJuzgado;
		this.tipoAsunto = tipoAsunto;
		this.ciudad = ciudad;
		this.numeroExpediente = numeroExpediente;
		this.asunAbogCliens = asunAbogCliens;
	}

	@Id

	@Column(name = "ID_ASUNTO", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdAsunto() {
		return this.idAsunto;
	}

	public void setIdAsunto(long idAsunto) {
		this.idAsunto = idAsunto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECRETARIA", nullable = false)
	public Secretaria getSecretaria() {
		return this.secretaria;
	}

	public void setSecretaria(Secretaria secretaria) {
		this.secretaria = secretaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JUZGADO", nullable = false)
	public CatalogoJuzgado getCatalogoJuzgado() {
		return this.catalogoJuzgado;
	}

	public void setCatalogoJuzgado(CatalogoJuzgado catalogoJuzgado) {
		this.catalogoJuzgado = catalogoJuzgado;
	}

	@Column(name = "TIPO_ASUNTO", length = 100)
	public String getTipoAsunto() {
		return this.tipoAsunto;
	}

	public void setTipoAsunto(String tipoAsunto) {
		this.tipoAsunto = tipoAsunto;
	}

	@Column(name = "CIUDAD", length = 50)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "NUMERO_EXPEDIENTE", length = 15)
	public String getNumeroExpediente() {
		return this.numeroExpediente;
	}

	public void setNumeroExpediente(String numeroExpediente) {
		this.numeroExpediente = numeroExpediente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asunto")
	public Set<AsunAbogClien> getAsunAbogCliens() {
		return this.asunAbogCliens;
	}

	public void setAsunAbogCliens(Set<AsunAbogClien> asunAbogCliens) {
		this.asunAbogCliens = asunAbogCliens;
	}

}
