package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AsunAbogClien generated by hbm2java
 */
@Entity
@Table(name = "ASUN_ABOG_CLIEN", schema = "CONSULTORIAJURIDICA")
public class AsunAbogClien implements java.io.Serializable {

	private long idAsuntoAbogadoCliente;
	private Abogado abogado;
	private Cliente cliente;
	private Asunto asunto;

	public AsunAbogClien() {
	}

	public AsunAbogClien(long idAsuntoAbogadoCliente, Abogado abogado, Cliente cliente, Asunto asunto) {
		this.idAsuntoAbogadoCliente = idAsuntoAbogadoCliente;
		this.abogado = abogado;
		this.cliente = cliente;
		this.asunto = asunto;
	}

	@Id

	@Column(name = "ID_ASUNTO_ABOGADO_CLIENTE", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdAsuntoAbogadoCliente() {
		return this.idAsuntoAbogadoCliente;
	}

	public void setIdAsuntoAbogadoCliente(long idAsuntoAbogadoCliente) {
		this.idAsuntoAbogadoCliente = idAsuntoAbogadoCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ABOGADO", nullable = false)
	public Abogado getAbogado() {
		return this.abogado;
	}

	public void setAbogado(Abogado abogado) {
		this.abogado = abogado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CLIENTE", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ASUNTO", nullable = false)
	public Asunto getAsunto() {
		return this.asunto;
	}

	public void setAsunto(Asunto asunto) {
		this.asunto = asunto;
	}

}
