package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoRamo generated by hbm2java
 */
@Entity
@Table(name = "CATALOGO_RAMO", schema = "CONSULTORIAJURIDICA")
public class CatalogoRamo implements java.io.Serializable {

	private long idRamo;
	private String nombre;
	private Set<Juzgado> juzgados = new HashSet<Juzgado>(0);

	public CatalogoRamo() {
	}

	public CatalogoRamo(long idRamo) {
		this.idRamo = idRamo;
	}

	public CatalogoRamo(long idRamo, String nombre, Set<Juzgado> juzgados) {
		this.idRamo = idRamo;
		this.nombre = nombre;
		this.juzgados = juzgados;
	}

	@Id

	@Column(name = "ID_RAMO", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdRamo() {
		return this.idRamo;
	}

	public void setIdRamo(long idRamo) {
		this.idRamo = idRamo;
	}

	@Column(name = "NOMBRE", length = 8)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoRamo")
	public Set<Juzgado> getJuzgados() {
		return this.juzgados;
	}

	public void setJuzgados(Set<Juzgado> juzgados) {
		this.juzgados = juzgados;
	}

}
