package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoJuzgado generated by hbm2java
 */
@Entity
@Table(name = "CATALOGO_JUZGADO", schema = "CONSULTORIAJURIDICA")
public class CatalogoJuzgado implements java.io.Serializable {

	private long idJuzgado;
	private String nombre;
	private Set<Juzgado> juzgados = new HashSet<Juzgado>(0);
	private Set<Asunto> asuntos = new HashSet<Asunto>(0);

	public CatalogoJuzgado() {
	}

	public CatalogoJuzgado(long idJuzgado) {
		this.idJuzgado = idJuzgado;
	}

	public CatalogoJuzgado(long idJuzgado, String nombre, Set<Juzgado> juzgados, Set<Asunto> asuntos) {
		this.idJuzgado = idJuzgado;
		this.nombre = nombre;
		this.juzgados = juzgados;
		this.asuntos = asuntos;
	}

	@Id

	@Column(name = "ID_JUZGADO", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdJuzgado() {
		return this.idJuzgado;
	}

	public void setIdJuzgado(long idJuzgado) {
		this.idJuzgado = idJuzgado;
	}

	@Column(name = "NOMBRE", length = 16)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoJuzgado")
	public Set<Juzgado> getJuzgados() {
		return this.juzgados;
	}

	public void setJuzgados(Set<Juzgado> juzgados) {
		this.juzgados = juzgados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogoJuzgado")
	public Set<Asunto> getAsuntos() {
		return this.asuntos;
	}

	public void setAsuntos(Set<Asunto> asuntos) {
		this.asuntos = asuntos;
	}

}
