package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE", schema = "CONSULTORIAJURIDICA")
public class Cliente implements java.io.Serializable {

	private long idCliente;
	private String nombre;
	private String ciudad;
	private String estadoRadicacion;
	private Long numeroCelular;
	private String correoElectronico;
	private Set<AsunAbogClien> asunAbogCliens = new HashSet<AsunAbogClien>(0);

	public Cliente() {
	}

	public Cliente(long idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(long idCliente, String nombre, String ciudad, String estadoRadicacion, Long numeroCelular,
			String correoElectronico, Set<AsunAbogClien> asunAbogCliens) {
		this.idCliente = idCliente;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.estadoRadicacion = estadoRadicacion;
		this.numeroCelular = numeroCelular;
		this.correoElectronico = correoElectronico;
		this.asunAbogCliens = asunAbogCliens;
	}

	@Id

	@Column(name = "ID_CLIENTE", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(long idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "CIUDAD", length = 50)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "ESTADO_RADICACION", length = 50)
	public String getEstadoRadicacion() {
		return this.estadoRadicacion;
	}

	public void setEstadoRadicacion(String estadoRadicacion) {
		this.estadoRadicacion = estadoRadicacion;
	}

	@Column(name = "NUMERO_CELULAR", precision = 15, scale = 0)
	public Long getNumeroCelular() {
		return this.numeroCelular;
	}

	public void setNumeroCelular(Long numeroCelular) {
		this.numeroCelular = numeroCelular;
	}

	@Column(name = "CORREO_ELECTRONICO", length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<AsunAbogClien> getAsunAbogCliens() {
		return this.asunAbogCliens;
	}

	public void setAsunAbogCliens(Set<AsunAbogClien> asunAbogCliens) {
		this.asunAbogCliens = asunAbogCliens;
	}

}
