package mx.consultoria.juridica.especializada.entities;
// ......Isaul Hdez.


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Abogado generated by ...
 */
@Entity
@Table(name = "EXCELL_DATES", schema = "CONSULTORIAJURIDICA")
public class ExcellDates implements java.io.Serializable {

	private String rfc;
	private String curp;
	private String nombre;
	private Long edad;


	public ExcellDates() {
	}
	

	public ExcellDates(String rfc, String curp, String nombre, Long edad) {
		this.rfc = rfc;
		this.curp = curp;
		this.nombre = nombre;
		this.edad = edad;
	}
	
	
	@Column(name = "RFC", length = 100)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}
	
	@Column(name = "CURP", length = 100)
	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}	
	
	@Column(name = "NOMBRE", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	@Column(name = "EDAD", length = 100)
	public Long getEdad() {
		return this.edad;
	}

	public void setEdad(Long edad) {
		this.edad = edad;
	}	

}
