package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoCasos generated by hbm2java
 */
@Entity
@Table(name = "HISTORICO_CASOS", schema = "CONSULTORIAJURIDICA")
public class HistoricoCasos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idHistoricoCasos;
	private String usuarioAlta;
	private Date fechaRegistro;
	private String nombreArchivo;
	private Blob documento;
	
	private byte[] documentoBy;

	public HistoricoCasos() {
	}

	public HistoricoCasos(long idHistoricoCasos) {
		this.idHistoricoCasos = idHistoricoCasos;
	}

	public HistoricoCasos(long idHistoricoCasos, String usuarioAlta, Date fechaRegistro, String nombreArchivo,
			byte[] documento) {
		this.idHistoricoCasos = idHistoricoCasos;
		this.usuarioAlta = usuarioAlta;
		this.fechaRegistro = fechaRegistro;
		this.nombreArchivo = nombreArchivo;
		this.documentoBy = documento;
	}

	@Id
 // @GeneratedValue -> esto te genera el id autoincrementable
	@Column(name = "ID_HISTORICO_CASOS", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdHistoricoCasos() {
		return this.idHistoricoCasos;
	}

	public void setIdHistoricoCasos(long idHistoricoCasos) {
		this.idHistoricoCasos = idHistoricoCasos;
	}

	@Column(name = "USUARIO_ALTA", length = 50)
	public String getUsuarioAlta() {
		return this.usuarioAlta;
	}

	public void setUsuarioAlta(String usuarioAlta) {
		this.usuarioAlta = usuarioAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_REGISTRO")
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "NOMBRE_ARCHIVO", length = 100)
	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

//	@Column(name = "DOCUMENTO")
//	public Blob getDocumento() {
//		return this.documento;
//	}
//
//	public void setDocumento(Blob documento) {
//		this.documento = documento;
//	}
	

	@Column(name = "DOCUMENTO")
	public byte[] getDocumentoBy() {
		return documentoBy;
	}

	public void setDocumentoBy(byte[] documentoBy) {
		this.documentoBy = documentoBy;
	}
	
	

}
