package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Juzgado generated by hbm2java
 */
@Entity
@Table(name = "JUZGADO", schema = "CONSULTORIAJURIDICA")
public class Juzgado implements java.io.Serializable {

	private long idJuzgadoPrimeraInstancia;
	private CatalogoJuzgado catalogoJuzgado;
	private CatalogoRamo catalogoRamo;

	public Juzgado() {
	}

	public Juzgado(long idJuzgadoPrimeraInstancia, CatalogoJuzgado catalogoJuzgado, CatalogoRamo catalogoRamo) {
		this.idJuzgadoPrimeraInstancia = idJuzgadoPrimeraInstancia;
		this.catalogoJuzgado = catalogoJuzgado;
		this.catalogoRamo = catalogoRamo;
	}

	@Id

	@Column(name = "ID_JUZGADO_PRIMERA_INSTANCIA", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdJuzgadoPrimeraInstancia() {
		return this.idJuzgadoPrimeraInstancia;
	}

	public void setIdJuzgadoPrimeraInstancia(long idJuzgadoPrimeraInstancia) {
		this.idJuzgadoPrimeraInstancia = idJuzgadoPrimeraInstancia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JUZGADO", nullable = false)
	public CatalogoJuzgado getCatalogoJuzgado() {
		return this.catalogoJuzgado;
	}

	public void setCatalogoJuzgado(CatalogoJuzgado catalogoJuzgado) {
		this.catalogoJuzgado = catalogoJuzgado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_RAMO", nullable = false)
	public CatalogoRamo getCatalogoRamo() {
		return this.catalogoRamo;
	}

	public void setCatalogoRamo(CatalogoRamo catalogoRamo) {
		this.catalogoRamo = catalogoRamo;
	}

}
