package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RolesUsuarios generated by hbm2java
 */
@Entity
@Table(name = "ROLES_USUARIOS", schema = "CONSULTORIAJURIDICA")
public class RolesUsuarios implements java.io.Serializable {

	private long idPermiso;
	private String permiso;

	public RolesUsuarios() {
	}

	public RolesUsuarios(long idPermiso) {
		this.idPermiso = idPermiso;
	}

	public RolesUsuarios(long idPermiso, String permiso) {
		this.idPermiso = idPermiso;
		this.permiso = permiso;
	}

	@Id

	@Column(name = "ID_PERMISO", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(long idPermiso) {
		this.idPermiso = idPermiso;
	}

	@Column(name = "PERMISO", length = 200)
	public String getPermiso() {
		return this.permiso;
	}

	public void setPermiso(String permiso) {
		this.permiso = permiso;
	}

}
