package mx.consultoria.juridica.especializada.entities;
// Generated 15/04/2022 12:52:41 PM by Hibernate Tools 4.0.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Secretaria generated by hbm2java
 */
@Entity
@Table(name = "SECRETARIA", schema = "CONSULTORIAJURIDICA")
public class Secretaria implements java.io.Serializable {

	private long idSecretaria;
	private String nombre;
	private Set<Asunto> asuntos = new HashSet<Asunto>(0);

	public Secretaria() {
	}

	public Secretaria(long idSecretaria) {
		this.idSecretaria = idSecretaria;
	}

	public Secretaria(long idSecretaria, String nombre, Set<Asunto> asuntos) {
		this.idSecretaria = idSecretaria;
		this.nombre = nombre;
		this.asuntos = asuntos;
	}

	@Id

	@Column(name = "ID_SECRETARIA", unique = true, nullable = false, precision = 11, scale = 0)
	public long getIdSecretaria() {
		return this.idSecretaria;
	}

	public void setIdSecretaria(long idSecretaria) {
		this.idSecretaria = idSecretaria;
	}

	@Column(name = "NOMBRE", length = 18)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secretaria")
	public Set<Asunto> getAsuntos() {
		return this.asuntos;
	}

	public void setAsuntos(Set<Asunto> asuntos) {
		this.asuntos = asuntos;
	}

}
